name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: behe/heroku-build@v1.1
        with:
          api-key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: "paulohsantosol@gmail.com"
          app-name: "fierce-peak-93408"
